language: cpp
dist: trusty

os:
  - linux

compiler:
  - gcc
  - clang

install:
  - |
    ## Install Google Test & Google Mock from sources
    git clone https://github.com/google/googletest
    cd googletest
    mkdir -p build && cd build
    cmake -DBUILD_GTEST=OFF -DBUILD_GMOCK=ON CMAKE_INSTALL_PREFIX=$HOME/.local ..
    make -j4
    make install
    cd -

script:
  - mkdir build && cd build
  - cmake -DGTEST_ROOT=$HOME/.local -DGMOCK_ROOT=$HOME/.local ..
  - make
  - make test